services:
  - type: web
    name: pak-admin
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_USERNAME
        value: han_jeu
      - key: ADMIN_PASSWORD
        value: 21022010@
      - key: DATABASE_URL
        fromDatabase:
          name: pak-db
          property: connectionString

databases:
  - name: pak-db
    plan: free
    region: singapore
